### ISSUE TITLE
anchor links do not count the navbar height

### ISSUE THREAD

**Issue by ryanruthart** [Phlow/feeling-responsive#154] opened 2017-07-28 20:24 UTC
I wasn't able to find an answer to this question. When I use anchor links they are hidden by the navbar so that I do not see my titles. Is there a padding option somewhere I can set to account for that? I think it would be a variable because the navbar could change height depending on the device you are using?

You can see this behaviour on the documentation for feeling-responsive (https://phlow.github.io/feeling-responsive/documentation/#responsive-videos) When you go to that link the title for the section does not show.

example:

![image](https://user-images.githubusercontent.com/8918816/28734929-f793a62a-7397-11e7-839f-40b022df6bd6.png)

**Comment by gilardh** [comment] 2019-12-04 17:02
Hi,
Did you find a solution for this issue ?
Best regards

**Comment by TWiStErRob** [comment] 2019-12-04 17:49
Dupe of #155?, see https://github.com/Phlow/feeling-responsive/issues/120#issuecomment-264236727 for a solution/workaround.

**Comment by gilardh** [comment] 2019-12-05 09:41
@TWiStErRob Thanks It's work. 

I send a PR https://github.com/Phlow/feeling-responsive/pull/196

**Comment by gilardh** [comment] 2019-12-05 12:29
I think this issue can be closed now.

**Comment by Phlow** [comment] 2019-12-05 12:40
Ah, I forgot.

**Closed as completed by Phlow** 2019-12-05 12:40 UTC
