### ISSUE TITLE
Blog page layout on iPhone

### ISSUE THREAD

**Issue by nhuanvd** [Phlow/feeling-responsive#63] opened 2015-11-21 02:09 UTC
I get the problem while view blog page on my iPhone device (iPhone 5s, iOs 9.1) but it fine with iPhone 5, iOS 7.

![img_0168](https://cloud.githubusercontent.com/assets/3131944/11315971/0b601610-902e-11e5-8ff3-a337587df444.jpg)

**Comment by nhuanvd** [comment] 2015-11-21 07:03
The bug also appear on Chrome 46.0.2490.76, Android 4.2.2

**Comment by Phlow** [comment] 2015-11-21 13:23
This seems no bug. The headline is to big. Put this inbetween:

```
&shy;
```

media&shy;element.js

https://en.wikipedia.org/wiki/Soft_hyphen

**Comment by TWiStErRob** [comment] 2015-11-21 13:28
What about the top menu not occupying the whole width? The "Responsive" is on a new line even though it could nicely fit on one line if full width was used. On my screen it fits, but the width is still not used fully:
![ezgif-1890009575](https://cloud.githubusercontent.com/assets/2906988/11318729/009ec5c0-905e-11e5-90e7-c769a72c54b6.gif)
The problem is the audio player width, that extends the width over 100% I think.

**Comment by Phlow** [comment] 2015-11-21 22:06
Ah, OK. Next problem to solve ;)

**Comment by Phlow** [comment] 2015-11-23 09:27
The bug was in _/include/_meta_information.html_ – On the page was a container missing, when there is no previous post. I added an else-statement...

```
            {% else %}
            <div class="small-5 columns text-right"></div><!-- /.small-4.columns -->
            {% endif %}
```

It solves the problem. Please check :)

**Comment by TWiStErRob** [comment] 2015-11-23 09:35
Top bar and audio still looks the same as the gif I posted at https://phlow.github.io/feeling-responsive/design/mediaelement_js/
The only thing changed is the bottom Archive button is no in the middle not at right.

**Comment by TWiStErRob** [comment] 2015-11-23 09:38
You can use Chrome to debug and test how it looks on the phone: https://developers.google.com/web/tools/chrome-devtools/iterate/device-mode/?hl=en
This will resemble the mobile experience more closely than shrinking the browser width to trigger small screen selectors.

**Comment by Phlow** [comment] 2015-11-23 09:39
Damn... Than I have to change the default-width in
- mediaelement-and-player.js
- mediaelement-and-player.min.js

from `defaultAudioWidth:400` to something smaller...

I didnt' want to work on the .js directly.

**Comment by TWiStErRob** [comment] 2015-11-23 09:41
If that's the "default" isn't there a way to config it, like you did for foundation at the end of the merged js?

**Comment by TWiStErRob** [comment] 2015-11-23 09:42
Or maybe there's a magic attribute on the player to set it.

**Comment by Phlow** [comment] 2015-11-23 09:43
I tried and searched. Couldn't find something else.

**Comment by Phlow** [comment] 2015-11-23 09:49
I made the changes and on top, I had to add `media&shy;element.js` because it broke things as well... I have to adjust the typography... It's to big for small devices. But this is something for the future. And there is foundation 6 now... Always something todo and to improve...

Sometimes I think I just should use the basics... Just plain old <audio> with no Javascript messing around...

**Comment by White-Rabbit-Scientific** [comment] 2016-01-02 00:26
Yes, keep it simple :-)

**Closed as completed** 2016-01-13 13:58 UTC
